const STORAGE_KEY = 'ryo-dnd-hud-v02';
const pages = ['Status','Combat','Magic','Inventory','Character','Backstory','Quests','Library','Settings'];
const allSkills = ['Acrobatics','Animal Handling','Arcana','Athletics','Deception','History','Insight','Intimidation','Investigation','Medicine','Nature','Perception','Performance','Persuasion','Religion','Sleight of Hand','Stealth','Survival'];
const skillStats = {Acrobatics:'DEX','Animal Handling':'WIS',Arcana:'INT',Athletics:'STR',Deception:'CHA',History:'INT',Insight:'WIS',Intimidation:'CHA',Investigation:'INT',Medicine:'WIS',Nature:'INT',Perception:'WIS',Performance:'CHA',Persuasion:'CHA',Religion:'INT','Sleight of Hand':'DEX',Stealth:'DEX',Survival:'WIS'};

const defaultState = {
  character:{name:'Ryo Dragneel',classes:'Warlock 4 / Paladin 2',level:6,pb:3,age:126,background:'Dragon Child',race:'Incubus-Elf',ac:16,initiative:0,speed:'9 m',inspiration:false,exhaustion:0,hpMax:57,hpCurrent:21,tempHp:8,hitDice:{d8:{current:4,max:4,label:'Warlock'},d10:{current:2,max:2,label:'Paladin'}},deathSaves:{success:0,fail:0},stats:{STR:16,DEX:10,CON:16,INT:9,WIS:16,CHA:19},baseCha:20,saves:['Wisdom','Charisma'],skills:['Athletics','Insight','Animal Handling','Persuasion','Perception'],languages:['Common','Draconic','Elvish','Infernal','Giant']},
  resources:{layOnHands:10,layOnHandsMax:10,divineSense:5,divineSenseMax:5,warlockSlots2:2,warlockSlots2Max:2,paladinSlots1:2,paladinSlots1Max:2,invokerSwitch:1,invokerSwitchMax:1},
  combat:{concentration:false,hex:false,conditions:[],attacks:[{name:'Greataxe of Ragna',bonus:'+8',damage:'1d12 + 5 slashing',notes:'Dragon-pact weapon. No charges currently.'},{name:'Oni-san',bonus:'+6',damage:'1d8 + 3 bludgeoning',notes:'Melee weapon.'},{name:'Dagger',bonus:'+6 / +3',damage:'1d4 + 3 piercing',notes:'Melee or ranged.'},{name:'Eldritch Blast',bonus:'+7',damage:'2 beams, 1d10 each',notes:'Spell attack.'}]},
  magic:{spellSaveDc:15,spellAttack:'+7',pact:'Fiend',boon:'Pact of the Invoker',activeInvoker:'Agonizing Blast',invokerChoices:['Agonizing Blast','Beast Speech','Eyes of the Rune Keeper'],alwaysInvocations:['Mask of Many Faces → Disguise Self','Heart of the Pact → Pact of the Tome'],tomeCantrips:['Guidance','Mage Hand','Resistance'],cantrips:['Eldritch Blast','Green-Flame Blade','Prestidigitation','Guidance','Mage Hand','Resistance'],spells:[
    s('Eldritch Blast','Cantrip','Warlock','Action','120 ft','Instant','Ranged spell attack. Two beams at character level 5+. Force damage.'),
    s('Green-Flame Blade','Cantrip','Warlock','Action','Self / 5 ft','Instant','Weapon attack; green fire can leap to a nearby creature.'),
    s('Prestidigitation','Cantrip','Warlock','Action','10 ft','Up to 1 hour','Small harmless magical effects, cleaning, flavoring, marks, trinkets.'),
    s('Guidance','Cantrip','Tome','Action','Touch','Concentration, up to 1 min','Touched creature adds 1d4 to one ability check.'),
    s('Mage Hand','Cantrip','Tome','Action','30 ft','1 min','Spectral hand manipulates unattended objects.'),
    s('Resistance','Cantrip','Tome','Action','Touch','Concentration, up to 1 min','Touched creature adds 1d4 to one saving throw.'),
    s('Distort Value','1st','Warlock','1 minute','Touch','8 hours','Make an object appear far more or less valuable.'),
    s('Hex','1st','Warlock','Bonus Action','90 ft','Concentration, up to 1 hour','Curse a target: extra necrotic damage when you hit; choose one ability for disadvantage on checks.'),
    s('Witch Bolt','1st','Warlock','Action','30 ft','Concentration, up to 1 min','Lightning link on hit; repeat damage with your action while maintained.'),
    s('Hold Person','2nd','Warlock','Action','60 ft','Concentration, up to 1 min','Paralyze a humanoid on a failed Wisdom save.'),
    s('Misty Step','2nd','Warlock','Bonus Action','Self','Instant','Teleport up to 30 ft to a visible unoccupied space.'),
    s('Bless','1st','Paladin','Action','30 ft','Concentration, up to 1 min','Up to three creatures add 1d4 to attacks and saving throws.',true),
    s('Command','1st','Paladin','Action','60 ft','1 round','One-word command; target obeys on failed Wisdom save.',true),
    s('Compelled Duel','1st','Paladin','Bonus Action','30 ft','Concentration, up to 1 min','Draw one creature into a duel if it fails a Wisdom save.'),
    s('Cure Wounds','1st','Paladin','Action','Touch','Instant','Heal a creature you touch.'),
    s('Detect Evil and Good','1st','Paladin','Action','Self','Concentration, up to 10 min','Sense certain creature types and consecrated/desecrated places.'),
    s('Detect Magic','1st','Paladin','Action','Self','Concentration, up to 10 min','Sense magic nearby and identify its school with sight.'),
    s('Detect Poison and Disease','1st','Paladin','Action','Self','Concentration, up to 10 min','Sense poisons, poisonous creatures, and diseases nearby.'),
    s('Divine Favor','1st','Paladin','Bonus Action','Self','Concentration, up to 1 min','Your weapon attacks deal extra radiant damage.'),
    s('Heroism','1st','Paladin','Action','Touch','Concentration, up to 1 min','Target cannot be frightened and gains temporary HP each turn.'),
    s('Protection from Evil and Good','1st','Paladin','Action','Touch','Concentration, up to 10 min','Protect against aberrations, celestials, elementals, fey, fiends, and undead.'),
    s('Purify Food and Drink','1st','Paladin','Action','10 ft','Instant','Purify nonmagical food and drink in a small area.'),
    s('Searing Smite','1st','Paladin','Bonus Action','Self','Concentration, up to 1 min','Next weapon hit deals fire damage and can ignite the target.',true),
    s('Shield of Faith','1st','Paladin','Bonus Action','60 ft','Concentration, up to 10 min','Target gains +2 AC.'),
    s('Thunderous Smite','1st','Paladin','Bonus Action','Self','Concentration, up to 1 min','Next weapon hit deals thunder damage and can push/prone.'),
    s('Wrathful Smite','1st','Paladin','Bonus Action','Self','Concentration, up to 1 min','Next weapon hit deals psychic damage and can frighten.',true)
  ],incubusMagic:[{name:'Slave',uses:6,notes:'Charm/domination themed.'},{name:'Receptacle',uses:3,notes:'Stored soul/essence themed.'},{name:'Mantra',uses:2,notes:'Calming/commanding influence.'},{name:'Libido',uses:3,notes:'Incubus influence.'},{name:'Triggered',uses:1,notes:'Conditional charm trigger.'},{name:'Task',uses:2,notes:'Set a directed task.'},{name:'Destruction',uses:3,notes:'Destructive impulse.'},{name:'Deep Focus',uses:1,notes:'Focus state.'},{name:'Sense',uses:2,notes:'Sense desire/emotion.'},{name:'Cumulative',uses:2,notes:'Stacking influence.'},{name:'Lesser',uses:1,notes:'Minor version.'},{name:'Siphoning',uses:2,notes:'Drain/siphon themed.'},{name:'Command',uses:3,notes:'Direct command.'}],notes:'Pact of the Invoker: your patron knows your Truename. Choose 3 invocations; one can be active. Once per short rest, switch the active invocation to one of the other two.'},
  inventory:{currency:{CP:0,SP:0,GP:0,PP:0},items:[{category:'Equipment',name:'Greataxe of Ragna',qty:1,notes:'No charges available yet.'},{category:'Equipment',name:'Chain Mail',qty:1,notes:'AC 16.'},{category:'Equipment',name:'Bag of Holding',qty:1,notes:''},{category:'Valuables',name:'Dragon Pipe',qty:1,notes:'Inherited.'}]},
  backstory:`In a distant past, Ryo Dragneel was born under the green hills while the sun still shone gently over them. From his dragon eyes and blond hair to his caring parents, he was raised in love and safety.\n\nThat changed when his idyllic homeland was attacked by the Drows. He fled into the forest and was taken in by an old man who was not truly human, but an ancient dragon named Ragna. Ragna became his father figure and taught him languages, fighting, and life in the wild.\n\nYears later, an avatar of Asmodeus appeared. Ryo lost control, attacked, and was forced into a pact after Ragna was killed. The pact and his dragon inheritance changed him: green hair, one demonic eye, one draconic eye, and a curse around his Charisma.\n\nRyo now travels to prevent further tragedies, protect others, honor Ragna, and hunt both devils and demons.`,
  quests:[{type:'Personal Quest',status:'Active',title:'Hunt the Patron',progress:'Find and destroy the fiend behind Ryo’s curse and pact.'}],library:[{category:'Lore',title:'Ragna',body:'Dragon mentor and father figure.'},{category:'NPC',title:'Asmodeus Avatar',body:'Linked to the pact origin and tragedy.'}],notes:''
};
function s(name,level,source,casting,range,duration,desc,prepared=false){return{name,level,source,casting,range,duration,desc,prepared};}
let state = loadState();
function loadState(){try{return merge(structuredClone(defaultState),JSON.parse(localStorage.getItem(STORAGE_KEY))||{});}catch{return structuredClone(defaultState);}}
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]) merge(a[k],b[k]); else a[k]=b[k];}return a;}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function el(tag,cls='',html=''){const x=document.createElement(tag);if(cls)x.className=cls;if(html)x.innerHTML=html;return x;}
const mod=v=>Math.floor((v-10)/2), signed=n=>n>=0?`+${n}`:`${n}`;
function initNav(){const nav=document.getElementById('nav');nav.innerHTML='';pages.forEach(p=>{const b=el('button','',p);b.onclick=()=>showPage(p.toLowerCase());b.dataset.page=p.toLowerCase();nav.appendChild(b);});}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));}
function page(id){const p=document.getElementById(id);p.innerHTML='';return p;}
function render(){document.getElementById('classLine').textContent=state.character.classes;document.getElementById('levelLine').textContent=state.character.level;document.getElementById('raceLine').textContent=state.character.race;document.querySelector('[data-bind="ac"]').textContent=state.character.ac;document.querySelector('[data-bind="hp"]').textContent=`${state.character.hpCurrent}/${state.character.hpMax}`;document.querySelector('[data-bind="cha"]').textContent=`${state.character.stats.CHA} (${signed(mod(state.character.stats.CHA))})`;document.querySelector('[data-bind="pb"]').textContent=signed(state.character.pb);renderStatus();renderCombat();renderMagic();renderInventory();renderCharacter();renderBackstory();renderQuests();renderLibrary();renderSettings();save();}
function hpHue(){const pct=Math.max(0,Math.min(1,state.character.hpCurrent/state.character.hpMax));return Math.round(pct*125);} 
function ring(label,current,max,type,onChange){const pct=Math.max(0,Math.min(100,max?current/max*100:0));const card=el('div','panel card stat-ring');const color=type==='hp'?`hsl(${hpHue()},88%,55%)`:type||'var(--accent)';card.innerHTML=`<div class="ring ${type==='hp'?'hp':''}" style="--pct:${pct}%;--color:${color};--hpHue:${hpHue()}"><div class="ring-inner"><div><p class="label">${label}</p><strong>${current}/${max}</strong></div></div></div><div class="bar" style="--pct:${pct}%;--color:${color}"><span></span></div>`;const c=el('div','controls');[-10,-5,-1,1,5,10].forEach(n=>{const b=el('button','',n>0?`+${n}`:n);b.onclick=()=>{onChange(n);render();};c.appendChild(b);});card.appendChild(c);return card;}
function counter(label,obj,key,maxKey,hint=''){const wrap=el('div','counter');wrap.innerHTML=`<div><p class="label">${label}</p><p class="hint">${hint}</p></div><div class="counter-controls"><button>-</button><strong>${obj[key]}/${obj[maxKey]}</strong><button>+</button></div>`;wrap.querySelector('button:first-child').onclick=()=>{obj[key]=Math.max(0,obj[key]-1);render();};wrap.querySelector('button:last-child').onclick=()=>{obj[key]=Math.min(obj[maxKey],obj[key]+1);render();};return wrap;}
function renderStatus(){const p=page('status');const g=el('div','grid grid-3');g.append(ring('HP',state.character.hpCurrent,state.character.hpMax,'hp',n=>state.character.hpCurrent=Math.max(0,Math.min(state.character.hpMax,state.character.hpCurrent+n))),ring('TEMP HP',state.character.tempHp,Math.max(1,state.character.tempHp||8),'var(--accent)',n=>state.character.tempHp=Math.max(0,state.character.tempHp+n)),ring('LAY ON HANDS',state.resources.layOnHands,state.resources.layOnHandsMax,'var(--dragon)',n=>state.resources.layOnHands=Math.max(0,Math.min(state.resources.layOnHandsMax,state.resources.layOnHands+n))));p.appendChild(g);
const r=el('div','grid grid-3');const res=el('div','panel card');res.innerHTML='<h2>Rest Resources</h2><div class="resource-list"></div>';res.querySelector('.resource-list').append(counter('Divine Sense',state.resources,'divineSense','divineSenseMax','1 + CHA modifier'),counter('Warlock Spell Slots Lv. 2',state.resources,'warlockSlots2','warlockSlots2Max','Refills on short rest'),counter('Paladin Spell Slots Lv. 1',state.resources,'paladinSlots1','paladinSlots1Max','Refills on long rest'),counter('Invoker Switch',state.resources,'invokerSwitch','invokerSwitchMax','Once per short rest'));
const hd=el('div','panel card');hd.innerHTML=`<h2>Hit Dice</h2>${Object.entries(state.character.hitDice).map(([die,v])=>`<div class="counter"><div><p class="label">${die} ${v.label}</p></div><div class="counter-controls"><input type="number" data-hd="${die}" data-field="current" value="${v.current}"><span>/</span><input type="number" data-hd="${die}" data-field="max" value="${v.max}"></div></div>`).join('')}`;
const ds=el('div','panel card',`<h2>Survival</h2><label class="toggle-line"><input id="insp" type="checkbox" ${state.character.inspiration?'checked':''}> Inspiration</label><label>Exhaustion <input id="exhaust" type="number" min="0" max="6" value="${state.character.exhaustion}"></label><h3>Death Saves</h3><p>Successes: ${'◆'.repeat(state.character.deathSaves.success)}${'◇'.repeat(3-state.character.deathSaves.success)}</p><p>Failures: ${'◆'.repeat(state.character.deathSaves.fail)}${'◇'.repeat(3-state.character.deathSaves.fail)}</p><div class="controls"><button id="dsS">Success</button><button id="dsF">Fail</button><button id="dsR">Reset</button></div>`);
r.append(res,hd,ds);p.appendChild(r);hd.querySelectorAll('input').forEach(i=>i.oninput=e=>{state.character.hitDice[e.target.dataset.hd][e.target.dataset.field]=Number(e.target.value)||0;save();});ds.querySelector('#insp').onchange=e=>{state.character.inspiration=e.target.checked;save();};ds.querySelector('#exhaust').oninput=e=>{state.character.exhaustion=Math.max(0,Math.min(6,Number(e.target.value)||0));save();};ds.querySelector('#dsS').onclick=()=>{state.character.deathSaves.success=Math.min(3,state.character.deathSaves.success+1);render();};ds.querySelector('#dsF').onclick=()=>{state.character.deathSaves.fail=Math.min(3,state.character.deathSaves.fail+1);render();};ds.querySelector('#dsR').onclick=()=>{state.character.deathSaves={success:0,fail:0};render();};}
function renderCombat(){const p=page('combat');const top=el('div','grid grid-3');top.innerHTML=`<div class="panel card"><h2>Combat State</h2><p><span class="badge ${state.combat.concentration?'warn':''}">Concentration: ${state.combat.concentration?'Active':'Off'}</span><span class="badge ${state.combat.hex?'warn':''}">Hex: ${state.combat.hex?'Active':'Off'}</span></p><div class="controls"><button id="conc">Toggle Concentration</button><button id="hex">Toggle Hex</button></div></div><div class="panel card"><h2>Defenses</h2><p>AC ${state.character.ac} · Initiative ${signed(state.character.initiative)} · Speed ${state.character.speed}</p><p>Saves: ${state.character.saves.map(x=>`<span class="badge">${x}</span>`).join('')}</p></div><div class="panel card"><h2>Conditions</h2><p>${state.combat.conditions.length?state.combat.conditions.map(c=>`<span class="badge danger">${c}</span>`).join(''):'No active conditions.'}</p><div class="form-row"><input id="conditionInput" placeholder="Add condition"><button id="addCondition">Add</button><button id="clearConditions">Clear</button></div></div>`;p.appendChild(top);const atk=el('div','panel card');atk.innerHTML='<h2>Attacks</h2>'+table(['Attack','Bonus','Damage','Notes'],state.combat.attacks.map(a=>[a.name,a.bonus,a.damage,a.notes]));p.appendChild(atk);top.querySelector('#conc').onclick=()=>{state.combat.concentration=!state.combat.concentration;render();};top.querySelector('#hex').onclick=()=>{state.combat.hex=!state.combat.hex;render();};top.querySelector('#addCondition').onclick=()=>{const v=top.querySelector('#conditionInput').value.trim();if(v)state.combat.conditions.push(v);render();};top.querySelector('#clearConditions').onclick=()=>{state.combat.conditions=[];render();};}
function renderMagic(){const p=page('magic');p.innerHTML=`<div class="grid grid-3"><div class="panel card"><h2>Spellcasting</h2><p>Spell Save DC <strong>${state.magic.spellSaveDc}</strong></p><p>Spell Attack <strong>${state.magic.spellAttack}</strong></p><p>CHA current ${state.character.stats.CHA} · base ${state.character.baseCha}</p></div><div class="panel card"><h2>Pact of the Invoker</h2><p>Patron: <span class="badge violet">${state.magic.pact}</span></p><p class="hint">The patron knows Ryo’s Truename. Choose 3 invocations; 1 active. Switch once per short rest.</p><h3>Active</h3><select id="activeInvoker">${state.magic.invokerChoices.map(x=>`<option ${x===state.magic.activeInvoker?'selected':''}>${x}</option>`).join('')}</select></div><div class="panel card"><h2>Slots</h2><div id="slotList" class="resource-list"></div></div></div>`;p.querySelector('#slotList').append(counter('Warlock Slots Lv. 2',state.resources,'warlockSlots2','warlockSlots2Max','Short rest'),counter('Paladin Slots Lv. 1',state.resources,'paladinSlots1','paladinSlots1Max','Long rest'));p.querySelector('#activeInvoker').onchange=e=>{state.magic.activeInvoker=e.target.value;render();};
const inv=el('div','grid grid-3');inv.innerHTML=`<div class="panel card"><h2>Always Active Invocations</h2>${badges(state.magic.alwaysInvocations)}</div><div class="panel card"><h2>Invoker Choices</h2>${badges(state.magic.invokerChoices.map(x=>x===state.magic.activeInvoker?'◆ '+x:x))}</div><div class="panel card"><h2>Incubus Magic</h2>${badges(state.magic.incubusMagic.map(x=>`${x.name} (${x.uses})`),'violet')}</div>`;p.appendChild(inv);
const spells=el('div','panel card');spells.innerHTML='<h2>Spell Cards</h2><div class="spell-grid">'+state.magic.spells.map((sp,i)=>`<article class="spell-card ${sp.prepared?'prepared':''}"><label class="toggle-line"><input type="checkbox" data-spell="${i}" ${sp.prepared?'checked':''}> Prepared / Active</label><h3>${sp.name}</h3><p><span class="badge">${sp.level}</span><span class="badge">${sp.source}</span></p><p><strong>Casting:</strong> ${sp.casting} · <strong>Range:</strong> ${sp.range}</p><p><strong>Duration:</strong> ${sp.duration}</p><p>${sp.desc}</p></article>`).join('')+'</div>';p.appendChild(spells);spells.querySelectorAll('[data-spell]').forEach(i=>i.onchange=e=>{state.magic.spells[e.target.dataset.spell].prepared=e.target.checked;save();e.target.closest('.spell-card').classList.toggle('prepared',e.target.checked);});const n=el('div','panel card');n.innerHTML=`<h2>Magic Notes</h2><textarea id="magicNotes">${state.magic.notes}</textarea>`;p.appendChild(n);n.querySelector('textarea').oninput=e=>{state.magic.notes=e.target.value;save();};}
function renderInventory(){const p=page('inventory');const cur=el('div','panel card');cur.innerHTML='<h2>Currency</h2><div class="grid grid-4">'+Object.keys(state.inventory.currency).map(k=>`<label>${k}<input type="number" data-cur="${k}" value="${state.inventory.currency[k]}"></label>`).join('')+'</div>';p.appendChild(cur);cur.querySelectorAll('input').forEach(i=>i.oninput=e=>{state.inventory.currency[e.target.dataset.cur]=Number(e.target.value);save();});const inv=el('div','panel card');inv.innerHTML='<h2>Inventory</h2>'+table(['Category','Item','Qty','Notes'],state.inventory.items.map(i=>[i.category,i.name,i.qty,i.notes]))+`<div class="small-form"><select id="cat"><option>Equipment</option><option>Magic Item</option><option>Consumable</option><option>Quest Item</option><option>Valuables</option><option>Miscellaneous</option></select><input id="qty" type="number" value="1"><input id="itemName" placeholder="Item name"><button id="addItem">Add</button></div>`;p.appendChild(inv);inv.querySelector('#addItem').onclick=()=>{const name=inv.querySelector('#itemName').value.trim();if(name)state.inventory.items.push({category:inv.querySelector('#cat').value,name,qty:Number(inv.querySelector('#qty').value)||1,notes:''});render();};}
function skillBonus(skill){const stat=skillStats[skill];return mod(state.character.stats[stat])+(state.character.skills.includes(skill)?state.character.pb:0)}
function renderCharacter(){const p=page('character');const stats=Object.entries(state.character.stats).map(([k,v])=>[k,v,signed(mod(v))]);const skillRows=allSkills.map(sk=>`<div class="skill-row"><span>${sk}</span><span>${skillStats[sk]}</span><strong>${signed(skillBonus(sk))}</strong><label><input type="checkbox" data-skill="${sk}" ${state.character.skills.includes(sk)?'checked':''}> prof</label></div>`).join('');p.innerHTML=`<div class="grid grid-2"><div class="panel card"><h2>Identity</h2><p>Name: ${state.character.name}</p><p>Age: ${state.character.age}</p><p>Race: ${state.character.race}</p><p>Background: ${state.character.background}</p><h2>Ability Scores</h2>${table(['Stat','Score','Mod'],stats)}<p class="hint">CHA is cursed: base 20, current 19.</p></div><div class="panel card"><h2>Skills</h2><div class="skill-row"><strong>Skill</strong><strong>Stat</strong><strong>Total</strong><strong></strong></div>${skillRows}</div></div><div class="panel card"><h2>Saving Throws & Languages</h2><h3>Saving Throws</h3>${badges(state.character.saves)}<h3>Languages</h3>${badges(state.character.languages)}</div>`;p.querySelectorAll('[data-skill]').forEach(ch=>ch.onchange=e=>{const sk=e.target.dataset.skill;if(e.target.checked&&!state.character.skills.includes(sk))state.character.skills.push(sk);if(!e.target.checked)state.character.skills=state.character.skills.filter(x=>x!==sk);render();});}
function renderBackstory(){const p=page('backstory');p.innerHTML=`<div class="panel card"><h2>Backstory</h2><textarea id="backstoryText">${state.backstory}</textarea></div>`;p.querySelector('#backstoryText').oninput=e=>{state.backstory=e.target.value;save();};}
function renderQuests(){const p=page('quests');p.innerHTML='<div class="panel card"><h2>Quests</h2>'+table(['Type','Status','Title','Progress'],state.quests.map(q=>[q.type,q.status,q.title,q.progress]))+`<div class="form-row"><input id="questTitle" placeholder="Quest title"><select id="questType"><option>Main Quest</option><option>Side Quest</option><option>Personal Quest</option><option>Hidden Quest</option></select><button id="addQuest">Add</button></div></div>`;p.querySelector('#addQuest').onclick=()=>{const title=p.querySelector('#questTitle').value.trim();if(title)state.quests.push({type:p.querySelector('#questType').value,status:'Active',title,progress:''});render();};}
function renderLibrary(){const p=page('library');p.innerHTML='<div class="panel card"><h2>Library Notes</h2><p class="hint">Player notes only. No unlock system.</p>'+table(['Category','Title','Note'],state.library.map(l=>[l.category,l.title,l.body]))+`<div class="form-row"><input id="libTitle" placeholder="Entry title"><select id="libCat"><option>NPC</option><option>Location</option><option>Faction</option><option>Enemy</option><option>Lore</option><option>Session Note</option></select><button id="addLib">Add</button></div></div>`;p.querySelector('#addLib').onclick=()=>{const title=p.querySelector('#libTitle').value.trim();if(title)state.library.push({category:p.querySelector('#libCat').value,title,body:''});render();};}
function renderSettings(){const p=page('settings');p.innerHTML=`<div class="grid grid-2"><div class="panel card"><h2>Data</h2><p>Stored locally in this browser.</p><div class="footer-actions"><button id="exportData">Export JSON</button><button id="importData">Import JSON</button><button id="resetData">Reset</button></div><textarea id="jsonBox"></textarea></div><div class="panel card"><h2>Rest Controls</h2><div class="footer-actions"><button id="shortRest">Short Rest</button><button id="longRest">Long Rest</button></div><p class="dragon-mark">◇ DRAGON SYSTEM INTERFACE ◇</p></div></div>`;p.querySelector('#exportData').onclick=()=>{p.querySelector('#jsonBox').value=JSON.stringify(state,null,2);};p.querySelector('#importData').onclick=()=>{try{state=JSON.parse(p.querySelector('#jsonBox').value);render();}catch{alert('Invalid JSON');}};p.querySelector('#resetData').onclick=()=>{if(confirm('Reset tracker data?')){state=structuredClone(defaultState);render();}};p.querySelector('#shortRest').onclick=()=>{state.resources.warlockSlots2=state.resources.warlockSlots2Max;state.resources.invokerSwitch=state.resources.invokerSwitchMax;render();};p.querySelector('#longRest').onclick=()=>{state.resources.warlockSlots2=state.resources.warlockSlots2Max;state.resources.paladinSlots1=state.resources.paladinSlots1Max;state.resources.layOnHands=state.resources.layOnHandsMax;state.resources.divineSense=state.resources.divineSenseMax;state.resources.invokerSwitch=state.resources.invokerSwitchMax;state.combat.conditions=[];state.combat.concentration=false;state.combat.hex=false;render();};}
function table(head,rows){return`<table class="table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function badges(arr,cls=''){return`<p>${arr.map(x=>`<span class="badge ${cls}">${x}</span>`).join('')}</p>`}
initNav();render();showPage('status');
