const KEY='ryoDragonArchive035';
const base={page:'status',character:{name:'Ryo Dragneel',level:6,classes:'Warlock 4 / Paladin 2',race:'Incubus-Elf',background:'Dragon Child',age:126,ac:16,pb:3,speed:'9 m',initiative:0,passivePerception:16,stats:{STR:16,DEX:10,CON:16,INT:9,WIS:16,CHA:19},baseCha:20},res:{hp:21,maxHp:57,tempHp:8,inspiration:false,exhaustion:0,hitDice:{d8:{cur:4,max:4},d10:{cur:2,max:2}},death:{success:0,fail:0},lay:10,layMax:10,sense:5,senseMax:5},slots:{warlock:{level:2,cur:2,max:2},paladin:{level:1,cur:2,max:2}},pact:{active:'Agonizing Blast',pool:['Agonizing Blast','Beast Speech','Eyes of the Rune Keeper'],notes:'Pact of the Invoker: your patron knows your Truename. You know three pact invocations, but only one is active. You can switch the active invocation with a 10 minute ritual, also as part of a short rest. Refreshes after a long rest.'},attacks:[{name:'Greataxe of Ragna',bonus:'+8',damage:'1d12 + 3 slashing',note:'Currently NOT using Charisma. Dragon pact/special effects are not active yet.'},{name:'Oni-san',bonus:'+6',damage:'1d8 + 3 bludgeoning',note:'Melee weapon.'},{name:'Dagger',bonus:'+6',damage:'1d4 + 3 piercing',note:'Melee or thrown.'},{name:'Eldritch Blast',bonus:'+7',damage:'1d10 force',note:'2 beams. Agonizing Blast only if active.'},{name:'Green-Flame Blade',bonus:'weapon',damage:'weapon + fire rider',note:'Use with melee weapon.'}],conditions:{Blinded:false,Charmed:false,Deafened:false,Frightened:false,Grappled:false,Incapacitated:false,Invisible:false,Paralyzed:false,Petrified:false,Poisoned:false,Prone:false,Restrained:false,Stunned:false,Unconscious:false,Exhausted:false},currency:{cp:0,sp:0,gp:0,pp:0},inventory:[{cat:'Equipment',name:'Chain Mail',qty:1,notes:'AC 16.'},{cat:'Equipment',name:'Greataxe of Ragna',qty:1,notes:'Special effects inactive.'},{cat:'Valuables',name:'Dragon Pipe',qty:1,notes:'Inherited.'},{cat:'Quest Items',name:'Draconic Amulet',qty:1,notes:'Fire resistance.'}],quests:[{type:'Personal Quest',status:'Active',title:'Hunt the Patron',details:'Find and destroy the fiend tied to Ryo’s pact.'},{type:'Main Quest',status:'Active',title:'Protect the Party',details:'An mir kommt ihr nicht vorbei.'}],library:[{cat:'Session Notes',title:'Open Notes',text:'Add campaign notes here.'},{cat:'Maps',title:'World Map',text:'Paste map notes or links here.'},{cat:'Lore',title:'Dragons',text:'Notes about dragons, myths and history.'}],backstory:`In einer längst vergangenen Zeit, als die Sonne noch zärtlich über die grünen Hügel schien, wurde ich, Ryo Dragneel, als Incubus-Elf mit strahlend blauen Augen und blondem Haar geboren. Die ersten drei Jahre meines Lebens waren von Liebe und Geborgenheit geprägt.

Doch das Schicksal nahm eine düstere Wendung. Mein idyllisches Heimatdorf fiel den Drows zum Opfer. Ich flüchtete in den nahegelegenen Wald, wo ich von einem alten Mann gefunden wurde, der eigentlich ein Drache von erstaunlicher Weisheit war. Unter seiner Anleitung lernte ich, nicht nur die Kunst des Kampfes, sondern auch Sprachen und Wahrheiten über Drachen.

Später trat Asmodeus in mein Leben. Der Avatar vernichtete meinen Ziehvater Ragna und zwang mich in einen Pakt. Mein Haar wurde tiefgrün, mein rechtes Auge wurde zu einem leuchtenden Drachenaue, mein linkes Auge zu einem glühend roten Dämonenauge mit schwarzem Mal.

Mit dem festen Entschluss, Tragödien wie diese zu verhindern, begab ich mich auf eine Reise, um Wesen aller Art zu beschützen, das Erbe der Drachen zu ehren und mich zugleich von meinem Pakt zu befreien.`};
const condDesc={Blinded:'Cannot see; attacks against you have advantage; your attacks have disadvantage.',Charmed:'Cannot attack charmer; charmer has advantage on social checks.',Deafened:'Cannot hear; automatically fail hearing checks.',Frightened:'Disadvantage while source is visible; cannot willingly move closer.',Grappled:'Speed becomes 0.',Incapacitated:'Cannot take actions or reactions.',Invisible:'Unseen; attacks against you have disadvantage; your attacks have advantage.',Paralyzed:'Incapacitated, cannot move/speak; attacks within 5 ft crit on hit.',Petrified:'Transformed, incapacitated, resistance to all damage.',Poisoned:'Disadvantage on attacks and ability checks.',Prone:'Only crawl; melee attacks against you have advantage.',Restrained:'Speed 0; attacks against you advantage; your attacks disadvantage.',Stunned:'Incapacitated, cannot move, can barely speak.',Unconscious:'Incapacitated, prone, drops held items; attacks within 5 ft crit.',Exhausted:'Track level separately on Status.'};
const skills=['Acrobatics DEX','Animal Handling WIS*','Arcana INT','Athletics STR*','Deception CHA','History INT','Insight WIS*','Intimidation CHA','Investigation INT','Medicine WIS','Nature INT','Perception WIS*','Performance CHA','Persuasion CHA*','Religion INT','Sleight of Hand DEX','Stealth DEX','Survival WIS'];
const saves=['STR','DEX','CON','INT','WIS*','CHA*'];
const spells=[
{name:'Eldritch Blast',src:'warlock',lvl:'Cantrip',prep:true,desc:'Ranged spell attack, 120 ft. Two beams at character level 5+. 1d10 force each.'},{name:'Green-Flame Blade',src:'warlock',lvl:'Cantrip',prep:true,desc:'Melee weapon attack; flame leaps to another creature.'},{name:'Prestidigitation',src:'warlock',lvl:'Cantrip',prep:true,desc:'Minor magical tricks, sensory effects, cleaning, flavoring, marks.'},{name:'Guidance',src:'pact',lvl:'Cantrip',prep:true,desc:'Add 1d4 to one ability check. Concentration.'},{name:'Mage Hand',src:'pact',lvl:'Cantrip',prep:true,desc:'Spectral hand manipulates objects at range.'},{name:'Resistance',src:'pact',lvl:'Cantrip',prep:true,desc:'Add 1d4 to one saving throw. Concentration.'},{name:'Hex',src:'warlock',lvl:'1st',prep:true,desc:'+1d6 necrotic when you hit target; disadvantage on chosen ability checks. Concentration.'},{name:'Witch Bolt',src:'warlock',lvl:'1st',prep:false,desc:'Lightning arc; repeat damage with action. Concentration.'},{name:'Distort Value',src:'warlock',lvl:'1st',prep:false,desc:'Object appears worth double or half. Concentration.'},{name:'Hold Person',src:'warlock',lvl:'2nd',prep:true,desc:'Paralyze a humanoid. Wisdom save. Concentration.'},{name:'Misty Step',src:'warlock',lvl:'2nd',prep:true,desc:'Bonus action teleport up to 30 ft.'},{name:'Burning Hands',src:'fiend',lvl:'1st',prep:true,desc:'15 ft cone, Dex save, 3d6 fire.'},{name:'Command',src:'fiend',lvl:'1st',prep:true,desc:'One-word command. Wisdom save.'},{name:'Bless',src:'paladin',lvl:'1st',prep:true,desc:'Up to 3 creatures add 1d4 to attacks and saves. Concentration.'},{name:'Cure Wounds',src:'paladin',lvl:'1st',prep:true,desc:'Touch heal 1d8 + spellcasting mod.'},{name:'Detect Magic',src:'paladin',lvl:'1st',prep:false,desc:'Sense magic within 30 ft. Concentration.'},{name:'Divine Favor',src:'paladin',lvl:'1st',prep:false,desc:'Weapon attacks deal +1d4 radiant. Concentration.'},{name:'Heroism',src:'paladin',lvl:'1st',prep:false,desc:'Immune to frightened; temp HP each turn. Concentration.'},{name:'Protection from Evil and Good',src:'paladin',lvl:'1st',prep:false,desc:'Protect against aberrations, celestials, elementals, fey, fiends, undead. Concentration.'},{name:'Shield of Faith',src:'paladin',lvl:'1st',prep:true,desc:'+2 AC. Bonus action. Concentration.'},{name:'Slave',src:'incubus',lvl:'Incubus 6',prep:false,desc:'Incubus magic note from your sheet.'},{name:'Triggered',src:'incubus',lvl:'Incubus 1',prep:true,desc:'Incubus magic note from your sheet.'},{name:'Messaging',src:'incubus',lvl:'Incubus 3',prep:false,desc:'Incubus magic note from your sheet.'},{name:'Deep Focus',src:'incubus',lvl:'Incubus 1',prep:true,desc:'Incubus magic note from your sheet.'},{name:'Siphoning',src:'incubus',lvl:'Incubus 2',prep:false,desc:'Incubus magic note from your sheet.'}];
let S=JSON.parse(localStorage.getItem(KEY)||'null')||base;function save(){localStorage.setItem(KEY,JSON.stringify(S));renderTop();}
const pages=['status','combat','magic','inventory','character','backstory','quests','library','settings'];
function mod(n){return Math.floor((n-10)/2)} function prof(has){return has?S.character.pb:0} function statMod(stat){return mod(S.character.stats[stat])}
function hpColor(){let p=S.res.hp/S.res.maxHp*100;return `linear-gradient(90deg,hsl(${p*1.2},90%,48%),hsl(${Math.max(p*1.2-15,0)},90%,38%))`}
function renderTop(){document.getElementById('identityLine').textContent=`${S.character.classes} · Level ${S.character.level} · ${S.character.race} · ${S.character.background}`;document.getElementById('topOrbs').innerHTML=[['AC',S.character.ac],['HP',`${S.res.hp}/${S.res.maxHp}`],['PB',`+${S.character.pb}`]].map(o=>`<div class="orb"><span>${o[0]}</span><b>${o[1]}</b></div>`).join('')}
function renderNav(){nav.innerHTML=pages.map(p=>`<button class="tab ${S.page==p?'active':''}" onclick="S.page='${p}';save();render()">${p}</button>`).join('')}
function render(){renderTop();renderNav();({status,combat,magic,inventory,character,backstory,quests,library,settings}[S.page])()}
function card(t,body,cls='span4',edit=''){return `<section class="card ${cls}"><h2>${t}</h2>${edit?`<button class="edit" onclick="${edit}">✎</button>`:''}${body}</section>`}
function status(){page.innerHTML=`<div class="grid">${card('Vital Core',`<div class="hpbar"><div class="hpfill" style="width:${Math.max(0,Math.min(100,S.res.hp/S.res.maxHp*100))}%;background:${hpColor()}">${S.res.hp}/${S.res.maxHp} HP · ${S.res.tempHp} Temp</div></div><p class="tagline">Green at full health, sinking through gold into red near death.</p><div class="resource-row"><button onclick="chg('res.hp',-1)">−</button><button onclick="chg('res.hp',1)">+</button><button onclick="openEdit('Vital Core',[['res.hp','Current HP'],['res.maxHp','Max HP'],['res.tempHp','Temp HP']])">Edit</button></div>`,'span5')}${card('Death Gate',deathHTML(),'span4')}${card('Focus & Wounds',`<label class="pill"><input type="checkbox" ${S.res.inspiration?'checked':''} onchange="S.res.inspiration=this.checked;save();render()"> Inspiration</label><div class="resource-row"><span>Exhaustion</span><button onclick="chg('res.exhaustion',-1,0,6)">−</button><b>${S.res.exhaustion}</b><button onclick="chg('res.exhaustion',1,0,6)">+</button></div>`,'span3')}${card('Hit Dice',Object.entries(S.res.hitDice).map(([k,v])=>`<div class="dice-row"><span class="pill">${k}</span><input class="tiny" type="number" value="${v.cur}" onchange="S.res.hitDice.${k}.cur=+this.value;save()"> / <input class="tiny" type="number" value="${v.max}" onchange="S.res.hitDice.${k}.max=+this.value;save()"></div>`).join(''),'span4')}${card('Sacred Oath',`<div class="resource-row"><span>Lay on Hands</span><input class="tiny" type="number" value="${S.res.lay}" onchange="S.res.lay=+this.value;save()"> / ${S.res.layMax}</div><div class="resource-row"><span>Divine Sense</span><input class="tiny" type="number" value="${S.res.sense}" onchange="S.res.sense=+this.value;save()"> / ${S.res.senseMax}</div>`,'span4')}${card('Spell Slots',slotsHTML(),'span4')}</div>`}
function deathHTML(){return `<p class="label">Successes</p><div class="death-orbs">${[1,2,3].map(i=>`<button class="death ok ${S.res.death.success>=i?'on':''}" onclick="S.res.death.success=${S.res.death.success==i?i-1:i};save();render()">✓</button>`).join('')}</div><p class="label">Failures</p><div class="death-orbs">${[1,2,3].map(i=>`<button class="death bad ${S.res.death.fail>=i?'on':''}" onclick="S.res.death.fail=${S.res.death.fail==i?i-1:i};save();render()">×</button>`).join('')}</div><div class="danger-line"></div>`}
function slotsHTML(){return ['warlock','paladin'].map(k=>`<div class="resource-row"><span>${k} Lv.${S.slots[k].level}</span><button onclick="chg('slots.${k}.cur',-1,0,S.slots.${k}.max)">−</button><b>${S.slots[k].cur}/${S.slots[k].max}</b><button onclick="chg('slots.${k}.cur',1,0,S.slots.${k}.max)">+</button></div>`).join('')}
function combat(){page.innerHTML=`<div class="grid">${card('Combat Pulse',`<div class="kv"><span>AC</span><b>${S.character.ac}</b><span>Initiative</span><b>${S.character.initiative>=0?'+':''}${S.character.initiative}</b><span>Speed</span><b>${S.character.speed}</b></div><div class="kv"><span>Concentration</span><label class="pill"><input type="checkbox"> Active</label><span>Hex</span><label class="pill"><input type="checkbox"> Active</label></div>`,'span12')}${card('Attacks',S.attacks.map(a=>`<div class="item"><b>${a.name}</b><span class="mod">${a.bonus}</span><p>${a.damage}</p><small>${a.note}</small></div>`).join(''),'span6')}${card('Saving Throws',saveHTML(),'span3')}${card('Conditions',`<div class="condition-grid">${Object.keys(S.conditions).map(c=>`<div class="condition ${S.conditions[c]?'active':''}" onclick="S.conditions['${c}']=!S.conditions['${c}'];save();render()"><b>${c}</b><p>${condDesc[c]}</p></div>`).join('')}</div>`,'span3')}</div>`}
function saveHTML(){return saves.map(x=>{let st=x.replace('*',''),p=x.includes('*'),v=statMod(st)+prof(p);return `<div class="pill">${st} <b class="mod">${v>=0?'+':''}${v}</b>${p?'◆':''}</div>`}).join('')}
function magic(){let order={incubus:4,paladin:3,fiend:2,warlock:1,pact:0};page.innerHTML=`<div class="grid">${card('Pact Nexus',`<p>${S.pact.notes}</p><div>${S.pact.pool.map(i=>`<label class="pill"><input type="radio" name="inv" ${S.pact.active==i?'checked':''} onchange="S.pact.active='${i}';save();render()"> ${i}</label>`).join('')}</div>`,'span12')}${card('Spellbook',`<div class="spell-grid">${spells.slice().sort((a,b)=>(b.prep-a.prep)||order[a.src]-order[b.src]).map(s=>`<article class="spell-card ${s.src} ${s.prep?'prepared':''}"><div class="spell-head"><b>${icon(s.src)} ${s.name}</b><span>${s.lvl}</span></div><p class="source">${s.src}${s.prep?' · prepared/active':''}</p><p>${s.desc}</p></article>`).join('')}</div>`,'span12')}</div>`}
function icon(s){return {warlock:'✦',fiend:'🔥',paladin:'✚',incubus:'♡',pact:'◈'}[s]||'✧'}
function inventory(){let cats=[...new Set(S.inventory.map(i=>i.cat))];page.innerHTML=`<div class="grid">${card('Currency',Object.entries(S.currency).map(([k,v])=>`<div class="resource-row"><span class="pill">${k.toUpperCase()}</span><input type="number" value="${v}" onchange="S.currency.${k}=+this.value;save()"></div>`).join(''),'span3')}${card('Inventory',cats.map(c=>`<details class="accordion" open><summary>${c}</summary><div class="item-grid">${S.inventory.filter(i=>i.cat==c).map((i,idx)=>`<div class="item"><b>${i.name}</b><span class="mod">×${i.qty}</span><textarea onchange="invNote('${i.name}',this.value)">${i.notes||''}</textarea></div>`).join('')}</div></details>`).join('')+`<button onclick="addItem()">+ Add Item</button>`,'span9')}</div>`}
function character(){page.innerHTML=`<div class="grid">${card('Ryo',`<div class="eye"></div>`,'span4 portrait-card')}${card('Identity',`<p><b>Race:</b> ${S.character.race}</p><p><b>Background:</b> ${S.character.background}</p><p><b>Age:</b> ${S.character.age}</p><p><b>Passive Perception:</b> ${S.character.passivePerception}</p><p><b>Languages:</b> Common, Draconic, Elvish, Infernal, Giant</p>`,'span4','openEdit("Identity",[["character.race","Race"],["character.background","Background"],["character.age","Age"],["character.passivePerception","Passive Perception"]])')}${card('Traits',`<div class="item"><b>Darkvision</b><p>18 m</p></div><div class="item"><b>Fey Ancestry</b><p>Advantage on saves against being charmed. Magic cannot put you to sleep.</p></div><div class="item"><b>Incubus Magic</b><p>Uses Charisma where possible. Some magic may be cast without spell slots.</p></div><div class="item"><b>Dark One’s Blessing</b><p>When you reduce a hostile creature to 0 HP, gain temporary HP.</p></div>`,'span4')}${card('Ability Scores',Object.entries(S.character.stats).map(([k,v])=>`<div class="pill">${k} <b>${v}</b> <span class="mod">${mod(v)>=0?'+':''}${mod(v)}</span></div>`).join(''),'span4')}${card('Saving Throws',saveHTML(),'span4')}${card('Skills',`<div class="skill-grid">${skills.map(s=>skillHTML(s)).join('')}</div>`,'span4')}</div>`}
function skillHTML(s){let [name,starp]=s.split(' '), stat=starp.replace('*',''), p=starp.includes('*'), val=statMod(stat)+prof(p);return `<div class="skill ${p?'prof':''}"><b>${name.replace(/_/g,' ')}</b><span class="mod">${val>=0?'+':''}${val}</span><small>${stat}${p?' · proficient':''}</small></div>`}
function backstory(){page.innerHTML=`<div class="grid">${card('Backstory',`<div class="backstory">${S.backstory}</div>`,'span12','openEdit("Backstory",[["backstory","Backstory","textarea"]])')}</div>`}
function quests(){page.innerHTML=`<div class="grid">${card('Quest Journal',S.quests.map((q,i)=>`<div class="quest" onclick="this.classList.toggle('open')"><span class="source">${q.type} · ${q.status}</span><h3>${q.title}</h3><div class="quest-detail">${q.details}<br><button onclick="event.stopPropagation();editQuest(${i})">Edit</button></div></div>`).join('')+`<button onclick="addQuest()">+ Add Quest</button>`,'span12')}</div>`}
function library(){let cats=[...new Set(S.library.map(n=>n.cat))];page.innerHTML=`<div class="grid">${card('Campaign Archive',cats.map(c=>`<details class="accordion" open><summary>${c}</summary>${S.library.filter(n=>n.cat==c).map((n,i)=>`<div class="note"><b>${n.title}</b><textarea onchange="libNote('${n.title}',this.value)">${n.text}</textarea></div>`).join('')}</details>`).join('')+`<button onclick="addNote()">+ Add Note</button>`,'span12')}</div>`}
function settings(){page.innerHTML=`<div class="grid">${card('Rest & Data',`<button onclick="longRest()">Long Rest</button> <button onclick="shortRest()">Short Rest</button> <button onclick="download()">Export Save</button> <button onclick="if(confirm('Reset local save?')){localStorage.removeItem(KEY);location.reload()}">Reset</button><p class="warn">Long Rest: HP full, spell slots restored, Lay on Hands and Divine Sense restored, hit dice set to max for emergency usability.</p>`,'span12')}</div>`}
function chg(path,delta,min=-999,max=999){let a=path.split('.'),o=S;while(a.length>1)o=o[a.shift()];o[a[0]]=Math.max(min,Math.min(max,(+o[a[0]]||0)+delta));save();render()}
function get(path){return path.split('.').reduce((o,k)=>o[k],S)}function set(path,val){let a=path.split('.'),o=S;while(a.length>1)o=o[a.shift()];o[a[0]]=isNaN(val)||val===''?val:+val}
function openEdit(title,fields){editTitle.textContent=title;editFields.innerHTML=fields.map(f=>`<label>${f[1]}${f[2]=='textarea'?`<textarea data-path="${f[0]}">${get(f[0])}</textarea>`:`<input data-path="${f[0]}" value="${get(f[0])}">`}</label>`).join('');editDialog.showModal();saveEdit.onclick=e=>{editFields.querySelectorAll('[data-path]').forEach(el=>set(el.dataset.path,el.value));save();setTimeout(render,0)}}
function invNote(n,v){S.inventory.find(i=>i.name==n).notes=v;save()}function libNote(n,v){S.library.find(i=>i.title==n).text=v;save()}
function addItem(){S.inventory.push({cat:prompt('Category?','Miscellaneous')||'Miscellaneous',name:prompt('Item name?','New Item')||'New Item',qty:1,notes:''});save();render()}function addQuest(){S.quests.push({type:'Side Quest',status:'Active',title:prompt('Quest title?','New Quest')||'New Quest',details:''});save();render()}function addNote(){S.library.push({cat:prompt('Category?','Session Notes')||'Session Notes',title:prompt('Title?','New Note')||'New Note',text:''});save();render()}function editQuest(i){let q=S.quests[i];q.status=prompt('Status',q.status)||q.status;q.details=prompt('Details',q.details)||q.details;save();render()}function longRest(){S.res.hp=S.res.maxHp;S.res.tempHp=0;S.res.lay=S.res.layMax;S.res.sense=S.res.senseMax;S.slots.warlock.cur=S.slots.warlock.max;S.slots.paladin.cur=S.slots.paladin.max;Object.values(S.res.hitDice).forEach(d=>d.cur=d.max);S.res.death={success:0,fail:0};save();render()}function shortRest(){S.slots.warlock.cur=S.slots.warlock.max;save();render()}function download(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='ryo-dragon-archive-save.json';a.click()}
render();
